<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="obj\Debug\net10.0\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net10.0\ProjectManagement.AssemblyInfo.cs" />
    <Compile Include="obj\Debug\net10.0\ProjectManagement.GlobalUsings.g.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="obj\Debug\net10.0\rpswa.dswa.cache.json" />
    <Content Include="obj\Debug\net10.0\staticwebassets.removed.txt" />
    <Content Include="obj\project.assets.json" />
    <Content Include="obj\ProjectManagement.csproj.nuget.dgspec.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\net10.0\" />
    <Folder Include="Migrations\" />
    <Folder Include="obj\Debug\net10.0\refint\" />
    <Folder Include="obj\Debug\net10.0\ref\" />
    <Folder Include="obj\Debug\net10.0\staticwebassets\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="obj\Debug\net10.0\ProjectManagement.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net10.0\ProjectManagement.assets.cache" />
    <None Include="obj\Debug\net10.0\ProjectManagement.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net10.0\ProjectManagement.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\project.nuget.cache" />
    <None Include="obj\ProjectManagement.csproj.nuget.g.props" />
    <None Include="obj\ProjectManagement.csproj.nuget.g.targets" />
  </ItemGroup>

</Project>
